version: '3'
services:
#    product_service:
#      build: .
#      restart: always
#      ports:
#        - "8085:8085"
#      links:
#        - mongo_db:app_db
    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      volumes:
        -  ./mongo:/data/db/
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
      image: mongo-express
#      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongo
      environment:
        - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

